version: '3.8'
services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - /app
    command: >
      sh -c "
        yarn install &&
        yarn build &&
        PORT=8000 node .output/server/index.mjs
      "
    networks:
      - network
  
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    command: sh -c "while [ ! -f /etc/letsencrypt/live/vabeat.co.jp/fullchain.pem ]; do sleep 1; done; nginx -g 'daemon off;'"
    depends_on:
      - app
    networks:
      - network
  
  certbot:
    image: certbot/certbot:amd64-v1.19.0
    container_name: certbot
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    entrypoint: sh -c "trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;"
    networks:
      - network

networks:
  network:
    driver: bridge