services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - /app
    command: >
      sh -c "
        yarn install &&
        yarn build &&
        PORT=8000 node .output/server/index.mjs
      "
    networks:
      - network

networks:
  network:
    driver: bridge